name: Deploy Docker to DockerHub
# test
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: fayzillodeveloper/codespaces-test:git-action-test
          cache-from: type=registry,ref=fayzillodeveloper/codespaces-test
          cache-to: type=registry,ref=fayzillodeveloper/codespaces-test
          build-args: |
            DOCKER_BUILDKIT=1
            BUILDKIT_INLINE_CACHE=1
            BUILDKIT_PROGRESS=plain
            BUILDKIT_NO_CACHE=1
            BUILDKIT_CACHE_IMPORT=1
            BUILDKIT_CACHE_EXPORT=1
            BUILDKIT_CACHE_REPO=fayzillodeveloper/codespaces-test
          labels: |
            org.opencontainers.image.source=https://github.com/fayzillo95/awssevrertest
            org.opencontainers.image.url=https://github.com/fayzillo95/awssevrertest
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=Codespaces Test
            org.opencontainers.image.description=This is a test image for Codespaces
